language: python
cache: pip

python:
  - 3.4
  - 3.5

env:
  - TOXENV=dj110-wt19
  - TOXENV=dj110-wt110
  - TOXENV=dj111-wt19
  - TOXENV=dj111-wt110

# Matrix of build options
matrix:
  include:
    - python: 3.5
      env: TOXENV=isort,flake8,docs

install:
  - pip install --upgrade pip wheel tox setuptools

script:
  - tox

# vim: sw=2
