language: python
cache: pip

# Matrix of build options
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-dj111-wt23,py35-dj20-wt23,py35-dj20-wt24,py35-dj20-wt25
    - python: 3.6
      env: TOXENV=py36-dj111-wt23,py36-dj20-wt23,py36-dj20-wt24,py36-dj20-wt25
    - python: 3.6
      env: TOXENV=isort,flake8,docs

install:
  - pip install --upgrade pip wheel tox setuptools

script:
  - tox

# vim: sw=2
