language: python
cache: pip

python:
  - 3.4
  - 3.5

env:
  - TOXENV=dj19-wt15
  - TOXENV=dj110-wt15
  - TOXENV=dj19-wt16
  - TOXENV=dj110-wt16
  - TOXENV=dj19-wt17
  - TOXENV=dj110-wt17
  - TOXENV=dj19-wt18
  - TOXENV=dj110-wt18
  - TOXENV=dj19-wt19
  - TOXENV=dj110-wt19

# Matrix of build options
matrix:
  include:
    - python: 3.5
      env: TOXENV=isort,flake8,docs

install:
  - pip install --upgrade pip wheel tox setuptools

script:
  - tox

# vim: sw=2
